<?php

// this will parse the urls and the get

// first generate the url
set_time_limit(0);

require_once "simple_html_dom.php";
require_once 'connection.php';
require_once "functions.php";
$results = ex_query("SELECT `Key` FROM ProcessVideos where `processed`='No'");
while($row = mysql_fetch_array($results))
			    {
			    
$row=$row[0];			    
$row = ex_query1Row("SELECT * 
FROM  `ProcessVideos` 
WHERE  `Key` =$row");
$key = $row["Key"];


$html = file_get_html('http://www.youtube.com' . $row["url"]);

// What do i need
// the imbeded link for the site the link generated by youtube itself
// cant you create that already ?
/// yes i can
//so ?

$youtubeVidID = substr($row["url"], 9);

// link for embed links  =
$embeded_Link = "<iframe width=\"720\" height=\"640\" src=\"http://www.youtube.com/embed/$youtubeVidID&autoplay=1\" frameborder=\"0\" allowfullscreen></iframe>";
$Username = "";
$description = "";
$videoimage = "http://i2.ytimg.com/vi/" . $youtubeVidID . "/hqdefault.jpg";
$title = "";
//foreach ($html->find('div[id=watch-container]') as $element) {

foreach ($html->find('body') as $element) {

	$s = explode('<', $element);

	for ($q = 0; $q < count($s); $q++) {
		$mainstring = $s[$q];
		// Find UserName
		if (strlen(strstr($mainstring, "link itemprop=\"url\" href=\"http://www.youtube.com/user/")) > 0) {
			
			$Username = substr($mainstring, 54);
			$Username = substr($Username, 0,strlen($Username)-9);
		}
		
		if (strlen(strstr($mainstring, "itemprop=\"name\" content=")) > 0) {
			
			$title = substr($mainstring, 30);
			$title =substr($title, 0,strlen($title)-7);
			

		}

		if (strlen(strstr($mainstring, "meta property=\"og:title\"")) > 0) {
			$title = $mainstring;
			$title = substr($name, 34, strlen($title) - 41);

		}

	}
}

foreach ($html->find("p[id=eow-description]") as $element) {

	$description = substr($element, 25);
	$description = substr($description, 0, strlen($description) - 4);
	
}
/*
echo "\n<br /> Name of Video is:" . $title;
echo "\n<br /> Description of Video is:" . $description;
echo "\n<br /> Embeded link of Video is: " . $embeded_Link;
echo "\n<br /> image of Video is: " . $videoimage;
echo "\n<br /> User Upload of Video is: " . $Username;
*/
//first create a user if he doesnt exist 
// well the link would not work ?
// we can change it later 
if(ex_query1RowAns("Select 1 from users where UserName='$Username'")!=1)
{
	// seems like i would have to check for a number that does not exist. 
	$nt = "no";
	
	while ($nt!="Done") {
		$random = rand (0 , 10000000000);
		if (ex_query1RowAns("Select 1 from users where ID= $random")!="1") {
			$nt="Done";
		}
		
	}
$query = "insert into users (ID,UserName,fblink) value('".$random."','$Username','/user/infiniteammoinc')";
ex_query($query);
}
$hash = genUhash();
$userid = ex_query1RowAns("Select ID from users where UserName ='$Username'");
if(ex_query1RowAns("Select 1 from video where videoImage ='$videoimage' and UserID='$userid'")!=1)
{
$query = "INSERT INTO video (VideoName ,mp4Path,webMPath ,Hash,videoImage,UserID,dtuploaded,site) VALUES (";
$query .= "'" . $title . "', '" . $embeded_Link . "','" . "" . "','" .$hash . "','" . $videoimage . "','$userid','". to_mysqlDate(time()) . "','Youtube')";

ex_query($query);

}
$videoid = ex_query1RowAns("Select ID from video where videoImage ='$videoimage' and UserID='$userid'");
if(ex_query1RowAns("Select 1 from videodesc where  VidID ='$videoid'")!=1)
{
$query = "Insert into videodesc(VidID,txtDesc) Values(" . $videoid . ",'" . $description . "')";
ex_query($query);
$query = "Insert into videocatinfo(hash,Category) Values('" .  $hash. "','" . $row['string1'] . "')";
ex_query($query);
$query = "Insert into views(Video_ID,Numwatched) Values('$videoid',0)";
ex_query($query);
}

// now to add description 



//now i should look at the videos to the side 
// nah 
//why not 
// well because its a .......
//ok then well lets clean everything up than
ex_query("UPDATE  `TMSprdDB`.`ProcessVideos` SET  `processed` =  'Yes' WHERE  `ProcessVideos`.`Key` =$key");
} 
?>
